import {
  LOW_CONFIDENCE_KEYWORD,
  type HandoverRule,
} from "@/services/handover/types";

export const DEFAULT_HANDOVER_RULES: HandoverRule[] = [
  {
    id: null,
    name: "Emergency or medical concern",
    category: "emergency",
    requestType: "emergency_assistance",
    keywords: ["emergency", "medical", "ambulance", "choking", "sick", "faint", "hurt"],
    responseMessage: "Restaurant staff should assist immediately with this urgent request.",
    priority: 100,
  },
  {
    id: null,
    name: "Allergy confirmation",
    category: "allergy",
    requestType: "allergy_confirmation",
    keywords: [
      "allergy",
      "allergic",
      "allergen",
      "gluten",
      "peanut",
      "nut",
      "nuts",
      "dairy",
      "milk",
      "egg",
      "soy",
      "sesame",
      "shellfish",
      "fish",
    ],
    responseMessage: "Restaurant staff should confirm allergy safety before the customer orders or eats.",
    priority: 90,
  },
  {
    id: null,
    name: "Complaint or manager request",
    category: "complaint",
    requestType: "complaint_support",
    keywords: ["complaint", "complain", "manager", "wrong", "unhappy", "refund", "problem"],
    responseMessage: "Restaurant staff should handle this service issue directly.",
    priority: 80,
  },
  {
    id: null,
    name: "Bill or payment request",
    category: "payment",
    requestType: "payment_assistance",
    keywords: ["bill", "pay", "payment", "card", "cash", "receipt", "split"],
    responseMessage: "Restaurant staff should help with payment or bill requests.",
    priority: 70,
  },
  {
    id: null,
    name: "Staff help requested",
    category: "staff_help",
    requestType: "staff_help",
    keywords: ["staff", "waiter", "waitress", "server", "help", "call someone"],
    responseMessage: "Restaurant staff should assist the customer directly.",
    priority: 60,
  },
  {
    id: null,
    name: "Unknown restaurant information",
    category: "unknown_information",
    requestType: "staff_help",
    keywords: [LOW_CONFIDENCE_KEYWORD],
    responseMessage: "Restaurant staff should confirm this because the answer was not available in the AI context.",
    priority: 10,
  },
];
